"""
validator.py

Validates and post-processes the LLM-generated ATS analysis by
removing inconsistencies, validating skills against the Master Profile,
eliminating duplicates, and ensuring the final response is reliable.
"""

import re
from copy import deepcopy

# ----------------------------------------
# Skill Aliases (Canonical -> Aliases)
# ----------------------------------------

SKILL_ALIASES = {
    "langchain": ["langchain"],
    "llms": [
        "llms",
        "large language models",
        "llm",
        "openai gpt",
        "anthropic claude",
        "llama",
        "mistral",
        "qwen",
    ],
    "rag": [
        "rag",
        "retrieval augmented generation",
        "retrieval-augmented generation",
    ],
    "sql": [
        "sql",
        "microsoft sql server",
        "mysql",
    ],
    "nosql": [
        "nosql",
        "mongodb",
        "cassandra",
        "redis",
    ],
    "chromadb": [
        "chromadb",
        "vector database",
        "vector databases",
    ],
    "embeddings": [
        "embedding",
        "embeddings",
        "vector embedding",
    ],
}


# ----------------------------------------
# Utilities
# ----------------------------------------

def normalize(text: str) -> str:
    return text.strip().lower()


# ----------------------------------------
# Extract Master Profile Skills
# ----------------------------------------

def extract_master_profile_skills(master_profile: dict):

    skills = set()

    skills_section = master_profile.get("skills", {})

    for values in skills_section.values():

        if isinstance(values, list):

            for skill in values:
                skills.add(normalize(skill))

    return skills


# ----------------------------------------
# Find Canonical Skill
# ----------------------------------------

def find_matching_skill(text: str, master_skills: set):
    """
    Searches the supplied text for any skill present in the
    Master Profile using exact matching and predefined aliases.

    Args:
        text: Sentence generated by the LLM.
        master_skills: Set of normalized Master Profile skills.

    Returns:
        Canonical skill name if found, otherwise None.
    """

    text = normalize(text)

    # ----------------------------------------
    # Exact Master Profile Skill Match
    # ----------------------------------------

    for skill in master_skills:

        pattern = r"\b" + re.escape(skill) + r"\b"

        if re.search(pattern, text, re.IGNORECASE):
            return skill

    # ----------------------------------------
    # Alias Match
    # ----------------------------------------

    for canonical, aliases in SKILL_ALIASES.items():

        for alias in aliases:

            pattern = r"\b" + re.escape(normalize(alias)) + r"\b"

            if re.search(pattern, text, re.IGNORECASE):

                if canonical == "sql":

                    has_sql = any(
                        sql_skill in master_skills
                        for sql_skill in [
                            "sql",
                            "ms sql server",
                            "microsoft sql server",
                            "mysql",
                        ]
                    )

                    if has_sql:
                        return "SQL"

                elif canonical == "nosql":

                    has_nosql = any(
                        db in master_skills
                        for db in [
                            "nosql",
                            "mongodb",
                            "redis",
                            "cassandra",
                        ]
                    )

                    if has_nosql:
                        return "NoSQL"

                elif canonical == "llms":
                    return "LLMs"

                else:
                    return canonical.title()

    return None


# ----------------------------------------
# Remove duplicates
# ----------------------------------------

def unique(values):

    seen = set()
    output = []

    for value in values:

        key = normalize(value)

        if key not in seen:
            output.append(value)
            seen.add(key)

    return output


# ----------------------------------------
# Main Validator
# ----------------------------------------

def validate_response(response: dict, master_profile: dict):
    """
    Validates the LLM response by:

    - Removing false missing skills
    - Validating weaknesses
    - Removing invalid recommendations
    - Eliminating duplicates
    - Validating ATS scores

    Args:
        response: JSON response generated by the LLM.
        master_profile: Parsed master profile containing validated skills.

    Returns:
        A cleaned and validated ATS analysis dictionary.
    """

    result = deepcopy(response)

    master_skills = extract_master_profile_skills(master_profile)

    matching = result.get("matching_skills", [])
    additional = result.get("additional_master_profile_skills", [])
    missing = result.get("missing_skills", [])
    weaknesses = result.get("weaknesses", [])

    matching_norm = {normalize(s) for s in matching}
    additional_norm = {normalize(s) for s in additional}

    # ----------------------------------------
    # Missing Skills Validation
    # ----------------------------------------

    corrected_missing = []

    for skill in missing:

        skill_norm = normalize(skill)

        if skill_norm in matching_norm:
            continue

        matched_skill = find_matching_skill(skill, master_skills)

        if matched_skill:

            if normalize(matched_skill) not in additional_norm:
                additional.append(matched_skill)
                additional_norm.add(normalize(matched_skill))

            continue

        corrected_missing.append(skill)

    result["missing_skills"] = unique(corrected_missing)
    result["additional_master_profile_skills"] = unique(additional)

    # ----------------------------------------
    # Weakness Validation
    # ----------------------------------------

    corrected_weaknesses = []

    for weakness in weaknesses:

        matched_skill = find_matching_skill(weakness, master_skills)

        if matched_skill:
            continue

        corrected_weaknesses.append(weakness)

    result["weaknesses"] = unique(corrected_weaknesses)

    # ----------------------------------------
    # Remove Duplicates
    # ----------------------------------------

    result["matching_skills"] = unique(result.get("matching_skills", []))
    result["strengths"] = unique(result.get("strengths", []))

    # ----------------------------------------
    # Recommendation Validation
    # ----------------------------------------

    filtered = []

    learning_keywords = [
        "learn",
        "gain experience",
        "become proficient",
        "develop",
        "acquire knowledge",
        "practice",
    ]

    for rec in result.get("recommendations", []):

        text = (
            rec.get("problem", "")
            + " "
            + rec.get("suggested_improvement", "")
        )

        matched_skill = find_matching_skill(text, master_skills)

        remove = False

        if matched_skill:

            lower = normalize(text)

            if any(keyword in lower for keyword in learning_keywords):
                remove = True

        if not remove:
            filtered.append(rec)

    result["recommendations"] = filtered

    # ----------------------------------------
    # Score Validation
    # ----------------------------------------

    result["ats_compatibility"] = max(
        0,
        min(100, int(result.get("ats_compatibility", 0))),
    )

    result["ats_quality"] = max(
        0,
        min(100, int(result.get("ats_quality", 0))),
    )

    return result

# ----------------------------------------
# Overall Summary Builder
# ----------------------------------------

def build_overall_summary(result: dict):

    missing = result.get("missing_skills", [])
    weaknesses = result.get("weaknesses", [])

    rating = result.get(
        "overall_recommendation", {}
    ).get(
        "rating",
        "Strong Match"
    )

    if not weaknesses and not missing:

        summary = (
            "The candidate is an excellent match for the role, demonstrating "
            "a strong technical profile with no major validated skill gaps."
        )

    elif weaknesses:

        summary = (
            "The candidate is a strong match for the role with a solid technical "
            "foundation. The primary areas for improvement are: "
            f"{', '.join(weaknesses)}."
        )

    else:

        summary = (
            "The candidate is a strong match for the role with relevant technical "
            "skills. The remaining validated skill gaps are: "
            f"{', '.join(missing)}."
        )

    result["overall_recommendation"] = {
        "rating": rating,
        "summary": summary,
    }

    return result